import datetime
import random
import logging
from ..models.schemas import GenerateResponse, LLMContentResponse
from .theme_engine import ThemeEngine
from ..infrastructure.weather_service import WeatherService
from .perfume_selector import PerfumeSelector
from ..prompts.content_prompts import ContentPromptBuilder
from ..infrastructure.llm.base import LLMProvider
from ..repositories.base import AbstractOutputRepository
from ..exceptions import WeatherServiceError, LLMValidationError

logger = logging.getLogger(__name__)

class ContentOrchestrator:
    def __init__(self,
                 theme_engine: ThemeEngine,
                 weather_service: WeatherService,
                 perfume_selector: PerfumeSelector,
                 prompt_builder: ContentPromptBuilder,
                 llm_provider: LLMProvider,
                 output_repository: AbstractOutputRepository):
        self.theme_engine = theme_engine
        self.weather_service = weather_service
        self.perfume_selector = perfume_selector
        self.prompt_builder = prompt_builder
        self.llm_provider = llm_provider
        self.output_repository = output_repository
        logger.info("ContentOrchestrator initialized with all injected abstractions.")

    async def generate_daily_content(self, perfume_id: Optional[int] = None) -> GenerateResponse:
        logger.info("Running content generation orchestration pipeline.")
        
        import zoneinfo
        LAGOS_TZ = zoneinfo.ZoneInfo("Africa/Lagos")
        now = datetime.datetime.now(tz=LAGOS_TZ)
        day_of_week = now.weekday()
        day_name_raw = now.strftime("%A")

        # 1. Day Context Setup (20% chance to explicitly reveal weekday name, handled by theme_engine)
        day_context = self.theme_engine.get_day_context(day_name_raw)

        time_of_day = self.theme_engine.get_time_of_day(now.hour)

        # 2. Weather context from WeatherService (graceful fallback)
        try:
            weather_context = await self.weather_service.get_current_weather()
        except WeatherServiceError as wse:
            logger.warning(f"WeatherService error: {wse.message}. Using safety fallback 'Unknown weather'.")
            weather_context = "Unknown weather"

        # 3. Theme selection rules
        week_of_month = self.theme_engine.get_week_of_month(now)
        active_category = self.theme_engine.get_category_for_date(now)
        theme_info = self.theme_engine.get_theme_for_date(now)

        is_generic = self.theme_engine.should_be_generic(day_of_week)

        # 4. Perfume selection
        selected_perfume = None
        if perfume_id is not None:
            selected_perfume = self.perfume_selector.repo.get_by_id(perfume_id)
            if selected_perfume:
                logger.info(f"Using explicitly requested perfume ID: {perfume_id} ({selected_perfume.perfume_name})")
            else:
                logger.warning(f"Explicit perfume ID {perfume_id} not found in database. Falling back to theme/category selection.")

        if not selected_perfume and not is_generic:
            selected_perfume = self.perfume_selector.select_perfume(active_category)

        perfume_name = "SirviniStyles Collection"
        brand = "SirviniStyles"
        if selected_perfume:
            perfume_name = selected_perfume.perfume_name
            brand = selected_perfume.brand

        # 5. Build prompt
        prompt = self.prompt_builder.build_full_prompt(
            day_context=day_context,
            time_of_day=time_of_day,
            weather=weather_context,
            day_of_week=day_of_week,
            theme_name=theme_info.name,
            objective=theme_info.objective,
            perfume=selected_perfume
        )

        # 6. Run LLM execution strategy
        ai_dict = self.llm_provider.generate_json(prompt)

        # 7. Model validation (coerce raw dictionary to Pydantic)
        try:
            logger.info("Validating parsed response dictionary through Pydantic LLMContentResponse model.")
            validated_response = LLMContentResponse.model_validate(ai_dict)
            ai_data = validated_response.model_dump()
            logger.info("Response matches schema validation criteria.")
        except Exception as ve:
            logger.error(f"Response validation failed: {ve}", exc_info=True)
            raise LLMValidationError(
                message="The response generated by the AI did not match the expected schema format.",
                detail=str(ve)
            )

        # 8. Output repository persist operations
        timestamp = now.strftime("%Y%m%d_%H%M%S")
        
        output_image_name = None
        image_url = None
        if selected_perfume and selected_perfume.image_filename:
            output_image_name = self.output_repository.copy_image(
                source_filename=selected_perfume.image_filename,
                timestamp=timestamp
            )
            if output_image_name:
                image_url = self.output_repository.get_image_url(selected_perfume.image_filename)

        # 9. Construct response contract
        response = GenerateResponse(
            perfume_id=selected_perfume.id if selected_perfume else None,
            perfume_name=perfume_name,
            brand=brand,
            theme=theme_info.name,
            week_of_month=week_of_month,
            active_category=active_category,
            is_generic=is_generic,
            main_post=ai_data.get("main_post", ""),
            whatsapp_sequence=ai_data.get("whatsapp_sequence", []),
            reel_script=ai_data.get("reel_script"),
            image_url=image_url,
            generated_image_file=output_image_name,
            hashtags=ai_data.get("hashtags"),
            keywords=ai_data.get("keywords"),
            hook=ai_data.get("hook"),
            cta=ai_data.get("cta"),
            image_prompt=ai_data.get("image_prompt"),
            engagement_question=ai_data.get("engagement_question")
        )

        # 10. Persist full response content
        self.output_repository.save_post(timestamp, response.model_dump())

        return response
